[[redirects]]
  from = "https://mitra2karangmojo.netlify.com/*"
  to = "https://mitra2karangmojo.com/:splat"
  status = 301
  force = true  
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  bundle = true
  minify = true
  pretty_urls = true
[build.processing.images]
  compress = true